### ISSUE TITLE
Add PsyOptions TVL to our landing page

### ISSUE THREAD

**Issue by stockmart** [mithraiclabs/landingpage#23]
We want to highlight the TVL of PsyOptions to everyone checking out PsyOptions, so it should be displayed on our landing page, and on trade.PsyOptions.io as well

**Comment by tomjohn1028** [comment]
[Example DeFi Llama code](https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/psyoptions/index.js)

Also see the [Bi-Dashboard codebase](https://github.com/mithraiclabs/bi-dashboard)

**Comment by tomjohn1028** [comment]
DeFi llama also has an API that makes this simple and likely more efficient for now

https://defillama.com/docs/api

**Comment by jasonhargrove** [comment]
Awesome!
