### ISSUE TITLE
Add partner logos to landing page

### ISSUE THREAD

**Issue by jasonhargrove** [mithraiclabs/landingpage#7]

**Comment by T-Wall** [comment]
Alameda Logo


![Alamedalogo](https://user-images.githubusercontent.com/91228741/139730336-d3abaf0f-d3a2-4cb8-a185-0210a31aff0f.jpeg)

**Comment by T-Wall** [comment]
GBV Logo

![GBVlogo](https://user-images.githubusercontent.com/91228741/139730419-ab4aa827-aa40-4df8-abb2-eaf04e2237d5.jpeg)

**Comment by T-Wall** [comment]
Solana Logo

![SolanaLogo](https://user-images.githubusercontent.com/91228741/139730573-52f8ca7b-4aaf-4705-b0d7-d8d1b918bb99.jpeg)

**Comment by T-Wall** [comment]
CMS Logo


![CMS](https://user-images.githubusercontent.com/91228741/139730846-27464158-2706-474f-8374-33a894be88bc.jpeg)

**Comment by T-Wall** [comment]
Wintermute Logo


![Wintermutelogo](https://user-images.githubusercontent.com/91228741/139731062-9552e464-ef63-45d1-8c32-39a8eaf5afd9.jpeg)

**Comment by T-Wall** [comment]
MGNR Logo


![MGNRLogo](https://user-images.githubusercontent.com/91228741/139731215-21f6e7a3-e602-4575-9b45-f4f37dc57151.jpeg)

**Comment by T-Wall** [comment]
Solar Eco Fund 


![SolarEchoFund-Logo](https://user-images.githubusercontent.com/91228741/139731408-e4358752-6c5c-4972-b62b-e36934f55145.jpeg)

**Comment by T-Wall** [comment]
LedgerPrime Logo


![LedgerPrimeLogo](https://user-images.githubusercontent.com/91228741/139731584-8904065f-2f30-47d1-acf5-d89a9b27b946.jpeg)

<img width="347" alt="Screen Shot 2021-11-01 at 12 46 09 PM" src="https://user-images.githubusercontent.com/91228741/139731996-d1957197-d5c7-45a5-994b-b21420796d34.png">

**Comment by T-Wall** [comment]
One Block Logo


![OneBlockLogo](https://user-images.githubusercontent.com/91228741/139732179-225a113a-32b2-4e2f-bb1f-d670603b09d0.jpeg)

**Comment by jasonhargrove** [comment]
![image](https://user-images.githubusercontent.com/285708/140163766-b0c7a0d0-5ab1-46c5-9c7d-824bf7fb32fd.png)
